return {
	armsnipe = {
		acceleration = 0.11999999731779,
		brakerate = 0.1879999935627,
		buildcostenergy = 0,
		buildcostmetal = 500,
		buildpic = "ARMSNIPE.DDS",
		buildtime = 5000,
		canmove = true,
		canCloak = true,
		mincloakdistance = 250,
		cloakCost = 0.0,
		stealth = true,
		initCloaked = true,
		decloakonfire = false,
		category = "KBOT MOBILE WEAPON ALL NOTSHIP NOTAIR NOTHOVER NOTSUB SURFACE a1",
		corpse = "DEAD",
		description = "Sniper Medium Infantry A1 D1 30MPS",
		explodeas = "BIG_UNITEX",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 140,
		maxslope = 14,
		maxvelocity = 1,
		maxwaterdepth = 22,
		movementclass = "KBOT2",
		name = "Sniper Infantry",
		nochasecategory = "VTOL",
		objectname = "ARMSNIPE",
		selfdestructas = "BIG_UNIT",
		sightdistance = 2000,
		smoothanim = true,
		turnrate = 1338,
		upright = true,
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-6.88437652588 -4.41893039551 -2.47041320801",
				collisionvolumescales = "49.6789398193 12.193939209 52.2985229492",
				collisionvolumetype = "Box",
				damage = 240,
				description = "Sharpshooter Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 322,
				object = "ARMSNIPE_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 120,
				description = "Sharpshooter Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 129,
				object = "2X2D",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
		weapondefs = {
			armsnipe_weapon = {
			accuracy = 150,
				areaofeffect = 0,
				collidefriendly = false,
				craterboost = 0,
				cratermult = 0,
				metalpershot = 30,
				explosiongenerator = "custom:FLASH1nd",
				impulseboost = 0.2339999973774,
				impulsefactor = 0.2339999973774,
				intensity = 0.75,
				interceptedByShieldType = 1,
				name = "Sniper",
				model = "missile",
				noselfdamage = true,
				range = 2000,
				reloadtime = 10,
				startvelocity = 3000,
				soundhit = "xplolrg2",
				soundhitvolume = 4,
				soundstart = "sniper2",
				soundstartvolume = 4,
				turret = true,
				texture2 = "coresmoketrail",
				weapontimer = 2,
				weapontype = "MissileLauncher",
				texture2 = "",
				weaponvelocity = 3000,
			
			
				damage = {
					commanders = 1025,
					default = 300,
					a2 = 10,
					a3 = 1,
					a1 = 300,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ARMSNIPE_WEAPON",
				onlytargetcategory = "a1",
			},
		},
	},
}
