return {
	corthud = {
		acceleration = 0.11299999803305,
		brakerate = 0.22499999403954,
		buildcostenergy = 0,
		buildcostmetal = 140,
		buildpic = "CORTHUD.DDS",
		buildtime = 1400,
		canmove = true,
		canCloak = true,
		mincloakdistance = 250,
		cloakCost = 0.0,
		stealth = true,
		initCloaked = true,
		category = "KBOT MOBILE WEAPON ALL NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE a1",
		corpse = "DEAD",
		description = "Short Range Armour Piercing Sabot Infantry A1 D3 25mps",
		energymake = 0.60000002384186,
		energyuse = 0.60000002384186,
		explodeas = "BIG_UNITEX",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		mass = 300,
		maxdamage = 140,
		maxslope = 14,
		maxvelocity = 2,
		maxwaterdepth = 12,
		movementclass = "KBOT2",
		name = "AP SabotInf",
		nochasecategory = "VTOL",
		objectname = "CORTHUD",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 800,
		smoothanim = true,
		trackoffset = 2,
		trackstrength = 8,
		trackstretch = 0.32499998807907,
		tracktype = "kbottrack1.bmp",
		trackwidth = 26,
		turnrate = 1099,
		upright = true,
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-1.26663208008 -3.12783955078 2.54402923584",
				collisionvolumescales = "27.809387207 16.8939208984 40.2852935791",
				collisionvolumetype = "Box",
				damage = 540,
				description = "Thud Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 96,
				object = "CORTHUD_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 270,
				description = "Thud Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 38,
				object = "2X2D",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			core_kbot_rocket = {
				accuracy = 200,
				areaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:VSMLMISSILE_EXPLOSION",
				firestarter = 70,
				impulseboost = 0.12300000339746,
				impulsefactor = 0.12300000339746,
				interceptedByShieldType = 128,
				metalpershot = 25,
				model = "missile",
				name = "Rockets",
				noselfdamage = true,
				range = 500,
				reloadtime = 10,
				smoketrail = true,
				soundhit = "xplosml2",
				soundstart = "rocklit1",
				startvelocity = 790,
				texture2 = "coresmoketrail",
				turret = true,
				weaponacceleration = -20,
				weapontimer = 2,
				weapontype = "MissileLauncher",
				weaponvelocity = 1190,
				damage = {
					a1 = 250,
					a2 = 250,
					a3 = 250,
					default = 100,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL A1",
				def = "CORE_KBOT_ROCKET",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
