return {
	armgate = {
		acceleration = 0,
		activatewhenbuilt = true,
		brakerate = 0,
		buildangle = 2048,
		buildcostenergy = 0,
		buildcostmetal = 50,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 4,
		buildinggrounddecalsizey = 4,
		buildinggrounddecaltype = "armdrag_aoplane.dds",
		buildpic = "ARMDRAG.DDS",
		buildtime = 1500,
		canmove = true,
		canCloak = true,
		mincloakdistance = 250,
		cloakCost = 0.0,
		decloakonfire = false,
		stealth = true,
		initCloaked = true,
		category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE a2",
		corpse = "DEAD",
		description = "Sheild Bunker",
		footprintx = 2,
		footprintz = 2,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 500,
		maxslope = 64,
		maxwaterdepth = 0,
		name = "Shield Bunker",
		objectname = "ARMDRAG.3do",
		onoffable = true,
		seismicsignature = 0,
		selfdestructas = "MINE_NUKE",
		sightdistance = 250,
		usebuildinggrounddecal = true,
		yardmap = "ffff",
		featuredefs = {
			dragonsteeth = {
				autoreclaimable = 0,
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "32 22 32",
				collisionvolumetest = 1,
				collisionvolumetype = "CylY",
				damage = 500,
				description = "Dragon's Teeth",
				featuredead = "RockTeeth",
				featurereclamate = "smudge01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 5,
				nodrawundergray = true,
				object = "armdrag",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "allworld",
			},
			rockteeth = {
				animating = 0,
				animtrans = 0,
				blocking = false,
				category = "heaps",
				damage = 500,
				description = "Rubble",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 2,
				object = "2X2A",
				reclaimable = true,
				shadtrans = 1,
				world = "greenworld",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "drone1",
			},
			select = {
				[1] = "drone1",
			},
		},
		weapondefs = {
			repulsor = {
				isshield = true,
				name = "Shield",
				range = 70,
				shieldalpha = 0.70000000596046,
				shieldbadcolor = "1 0 1",
				shieldenergyuse = 0,
				shieldforce = 4,
				shieldgoodcolor = "0 0 0",
				shieldintercepttype = 1,
				shieldmaxspeed = 1500,
				shieldpower = 5000,
				shieldpowerregen = 50,
				shieldpowerregenenergy = 0,
				shieldradius = 70,
				shieldrepulser = false,
				shieldstartingpower = 500,
				smartshield = true,
				visibleshield = false,
				visibleshieldhitframes = 70,
				visibleshieldrepulse = true,
				weapontype = "Shield",
				damage = {
					default = 100,
				},
			},
		},
		weapons = {
			[1] = {
				def = "REPULSOR",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
