return {
	cormort = {
		acceleration = 0.13199999928474,
		brakerate = 0.22499999403954,
		buildcostenergy = 0,
		buildcostmetal = 500,
		buildpic = "CORMORT.DDS",
		buildtime = 5000,
		canmove = true,
		canCloak = true,
		mincloakdistance = 250,
		cloakCost = 0.0,
		stealth = true,
		initCloaked = true,
		category = "KBOT MOBILE WEAPON ALL NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE a1",
		corpse = "DEAD",
		description = "Extreme Long Range Mortar Infantry A1 D1 30mps",
		explodeas = "BIG_UNITEX",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 280,
		maxslope = 14,
		maxvelocity = 0.75,
		maxwaterdepth = 12,
		movementclass = "KBOT2",
		name = "AOE Mortar Infantry",
		nochasecategory = "VTOL",
		objectname = "CORMORT",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 500,
		smoothanim = true,
		turnrate = 1099,
		upright = true,
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-2.46048736572 -3.00319400146 6.99045562744",
				collisionvolumescales = "41.948348999 14.0481719971 51.4421844482",
				collisionvolumetype = "Box",
				damage = 510,
				description = "Morty Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 118,
				object = "CORMORT_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 255,
				description = "Morty Heap",
				energy = 0,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 47,
				object = "2X2A",
				reclaimable = true,
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
		
			core_mort = {
				
				accuracy = 1900,
				areaofeffect = 450,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.05,
				explosiongenerator = "custom:FLASHBIGBUILDING",
				firestarter = 70,
				impulseboost = 0.12300000339746,
				impulsefactor = 0.5,
				interceptedByShieldType = 1,
				metalpershot = 30,
				model = "missile",
				name = "Rockets",
				noselfdamage = true,
				range = 4000,
				reloadtime = 20,
				smoketrail = true,
				soundhit = "xplonuk1",
				soundstart = "xplonuk4",
				startvelocity = 1090,
				texture2 = "coresmoketrail",
				turret = true,
				weaponacceleration = -40,
				weapontimer = 2,
				weapontype = "MissileLauncher",
				weaponvelocity = 1090,
				trajectoryHeight = 0.9,
				damage = {
					a1 = 79,
					a2 = 2,
					a3 = 1,
					default = 79,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL A2 a3",
				def = "CORE_MORT",
				onlytargetcategory = "SURFACE",
				
			},
		},
	},
}
