return {
	packo = {
		acceleration = 0,
		airsightdistance = 0,
		brakerate = 0,
		buildangle = 8192,
		buildcostenergy = 0,
		buildcostmetal = 200,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 5,
		buildinggrounddecalsizey = 5,
		buildinggrounddecaltype = "packo_aoplane.dds",
		buildpic = "PACKO.DDS",
		buildtime = 5810,
		category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE a2",
		canCloak = true,
		mincloakdistance = 200,
		cloakCost = 0.0,
		stealth = true,
		initCloaked = true,
		corpse = "DEAD",
		damagemodifier = 1,
		description = "Pop-Up Missile Battery",
		explodeas = "BIG_UNITEX",
		footprintx = 3,
		footprintz = 3,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 300,
		maxslope = 10,
		maxwaterdepth = 0,
		name = "Pack0",
		nochasecategory = "ALL",
		objectname = "PACKO",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 200,
		usebuildinggrounddecal = true,
		transportcapacity = 10,
        transportmass = 500000,
		transportsize = 30,
		loadingRadius = 5000,
		isFirePlatform = true,
		yardmap = "ooooooooo",
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-0.544990539551 0.0 -0.500007629395",
				collisionvolumescales = "48.1152496338 19.0 48.1152496338",
				collisionvolumetype = "Box",
				damage = 720,
				description = "Pack0 Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				hitdensity = 100,
				metal = 275,
				object = "PACKO_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 360,
				description = "Pack0 Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 4,
				hitdensity = 100,
				metal = 110,
				object = "3X3B",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			cloak = "kloak2",
			uncloak = "kloak2un",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servmed1",
			},
			select = {
				[1] = "servmed1",
			},
		},
		
		weapons = {
			[1] = {
				badtargetcategory = "NOTAIR",
				def = "",
				onlytargetcategory = "VTOL",
			},
		},
	},
}
